# Generated by Django 2.2.2 on 2019-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="bio", field=models.TextField(blank=True),
        ),
    ]
