# Generated by Django 2.2.2 on 2019-07-20 22:26

import django.contrib.postgres.fields
from django.db import migrations, models

import localhub.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190709_2059")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("comments", "Someone comments on my post"),
                        ("deletes", "A moderator deletes my post or comment"),
                        ("edits", "A moderator edits my post or comment"),
                        ("follows", "Someone I'm following creates a post"),
                        ("flags", "Someone flags a post or comment (MODERATORS ONLY)",),
                        ("likes", "Someone likes my post or comment"),
                        ("mentions", "I am @mentioned in a post or comment"),
                        ("messages", "Someone sends me a direct message"),
                        (
                            "tags",
                            "Someone creates a post containing a tag I'm following",
                        ),
                        (
                            "updates",
                            "Someone creates or updates content on site (MODERATORS ONLY)",
                        ),
                    ],
                    max_length=12,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
