# Generated by Django 2.2.2 on 2019-07-31 17:51

from django.db import migrations, models

import localhub.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190730_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_page_filters',
            field=localhub.core.db.fields.ChoiceArrayField(base_field=models.CharField(choices=[('users', "Posts from people I'm following"), ('tags', "Posts containing tags I'm following")], max_length=12), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='show_sensitive_content',
            field=models.BooleanField(default=False),
        ),
    ]
