# Generated by Django 2.2.4 on 2019-08-15 08:42

from django.db import migrations, models

import localhub.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_auto_20190812_0720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_preferences",
            field=localhub.db.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("new_message", "I receive a direct message"),
                        ("new_follower", "Someone starts following me"),
                        ("new_member", "Someone joins a community I belong to"),
                        ("new_comment", "Someone comments on my post"),
                        ("reshare", "Someone has reshared my post"),
                        ("mention", "I am @mentioned in a post or comment"),
                        ("moderator_delete", "A moderator deletes my post or comment"),
                        ("moderator_edit", "A moderator edits my post or comment"),
                        ("like", "Someone likes my post or comment"),
                        (
                            "new_followed_user_post",
                            "Someone I'm following creates a post",
                        ),
                        (
                            "new_followed_tag_post",
                            "A post is created containing tags I'm following",
                        ),
                        (
                            "flag",
                            "A user has flagged a comment or post (moderators only)",
                        ),
                        (
                            "moderator_review_request",
                            "A user has a new comment or post for you to review (moderators only)",
                        ),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
