# Generated by Django 2.2.4 on 2019-08-16 12:55

from django.db import migrations, models
import localhub.common.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190815_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_preferences',
            field=localhub.common.db.fields.ChoiceArrayField(base_field=models.CharField(choices=[('new_message', 'I receive a direct message'), ('new_follower', 'Someone starts following me'), ('new_member', 'Someone joins a community I belong to'), ('new_comment', 'Someone comments on my post, event or photo'), ('new_sibling_comment', "Someone comments on a post, event or photo I've also commented on"), ('reshare', 'Someone has reshared my post, event or photo'), ('mention', 'I am @mentioned in a post, event, photo or comment'), ('moderator_delete', 'A moderator deletes my post, event, photo or comment'), ('moderator_edit', 'A moderator edits my post, event, photo or comment'), ('like', 'Someone likes my post, event, photo or comment'), ('new_followed_user_post', "Someone I'm following submits a post, event or photo"), ('new_followed_user_comment', "Someone I'm following submits a comment"), ('new_followed_tag_post', "A post, event or photo is submitted containing tags I'm following"), ('flag', 'A user has flagged a comment, post, event or photo (moderators only)'), ('moderator_review_request', 'A user has a new comment, post, event or photo for you to review (moderators only)')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_page_filters',
            field=localhub.common.db.fields.ChoiceArrayField(base_field=models.CharField(choices=[('users', "Posts, events and photots from people I'm following"), ('tags', "Posts, events and photos containing tags I'm following")], max_length=12), blank=True, default=list, size=None),
        ),
    ]
