# Generated by Django 2.2.9 on 2020-01-15 22:46

from django.db import migrations

import localhub.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200107_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=localhub.markdown.fields.MarkdownField(blank=True),
        ),
    ]
