# Generated by Django 3.0.3 on 2020-03-09 19:53

from django.db import migrations, models
import localhub.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200308_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email_on_message',
            field=models.BooleanField(default=True, verbose_name='Send me an email when I receive a new Direct Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_email_on_notification',
            field=models.BooleanField(default=True, help_text='You can filter which Notifications you receive under the Notification preferences list.', verbose_name='Send me an email when I receive a new Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_webpush_on_message',
            field=models.BooleanField(default=True, help_text="To enable browser notifications, click 'Enable browser notifications' under Notifications. Your browser and device must also be granted permission to display notifications.", verbose_name='Show a browser notification when I receive a new Direct Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_webpush_on_notification',
            field=models.BooleanField(default=True, help_text="You can filter which Notifications you receive under the Notification preferences list. To enable browser notifications, click 'Enable browser notifications' under Notifications. Your browser and device must also be granted permission to display notifications.", verbose_name='Send me a browser notification when I receive a new Notification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_stream_filters',
            field=localhub.db.fields.ChoiceArrayField(base_field=models.CharField(choices=[('users', "Limited to only content from people I'm following"), ('tags', "Limited to only tags I'm following")], max_length=12), blank=True, default=list, size=None, verbose_name='Activity Stream Filters'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=localhub.db.fields.ChoiceArrayField(base_field=models.CharField(choices=[('new_follower', 'Someone has started following me'), ('new_member', 'Someone has joined a community I belong to'), ('new_comment', 'Someone has commented on one of my activities'), ('replied_to_comment', 'Someone has replied to one of my comments'), ('new_sibling_comment', "Someone has commented on an activity I've also commented on"), ('like', 'Someone has liked one of my activities or comments'), ('reshare', 'Someone has reshared one of my activities'), ('mention', 'I have been @mentioned in an activity or comment'), ('moderator_delete', 'A moderator has deleted one of my activities or comments'), ('moderator_edit', 'A moderator has edited one of my activities or comments'), ('new_followed_user_post', "Someone I'm following has posted an activity"), ('new_followed_user_comment', "Someone I'm following has posted a comment"), ('new_followed_tag_post', "An activity has been posted containing tags I'm following"), ('flag', 'A user has flagged content they are concerned about (community moderators only)'), ('moderator_review_request', 'A user has posted content for me to review (community moderators only)')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
