# Generated by Django 3.0.4 on 2020-04-01 22:04

import django.contrib.auth.validators
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models

import localhub.db.fields
import localhub.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_user_show_external_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Full name"
                    ),
                ),
                ("bio", localhub.markdown.fields.MarkdownField(blank=True)),
                ("avatar", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fi", "Suomi")],
                        default="en",
                        max_length=6,
                    ),
                ),
                (
                    "default_timezone",
                    timezone_field.fields.TimeZoneField(default="UTC"),
                ),
                (
                    "activity_stream_filters",
                    localhub.db.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "users",
                                    "Limited to only content from people I'm following",
                                ),
                                ("tags", "Limited to only tags I'm following"),
                            ],
                            max_length=12,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("show_external_images", models.BooleanField(default=True)),
                ("show_sensitive_content", models.BooleanField(default=False)),
                ("show_embedded_content", models.BooleanField(default=False)),
                ("send_email_notifications", models.BooleanField(default=True)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
