# Generated by Django 3.0.5 on 2020-04-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_auto_20200405_2202"),
    ]

    operations = [
        migrations.DeleteModel(name="HistoricalUser",),
    ]
