# Generated by Django 2.2.2 on 2019-07-29 21:18

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_auto_20190727_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
