# Generated by Django 3.0.2 on 2020-02-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20191121_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpost',
            old_name='metadata_description',
            new_name='opengraph_description',
        ),
        migrations.RenameField(
            model_name='historicalpost',
            old_name='metadata_image',
            new_name='opengraph_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='metadata_description',
            new_name='opengraph_description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='metadata_image',
            new_name='opengraph_image',
        ),
    ]
