# Generated by Django 3.0.3 on 2020-02-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200202_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
