# Generated by Django 3.0.5 on 2020-04-19 13:30

from django.db import migrations, models

import localhub.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0021_auto_20200407_2251"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="mentions",
            field=models.CharField(
                blank=True,
                max_length=300,
                validators=[localhub.users.validators.validate_mentions],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="mentions",
            field=models.CharField(
                blank=True,
                max_length=300,
                validators=[localhub.users.validators.validate_mentions],
            ),
        ),
    ]
