# Generated by Django 3.0.5 on 2020-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0025_auto_20200422_1856"),
    ]

    operations = [
        migrations.DeleteModel(name="HistoricalPost",),
    ]
