#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

echo "RUNNING GUNICORN UNDER PORT $PORT"
# move this migrate command to gitlab config
# ./manage.py migrate
gunicorn --bind=0.0.0.0:$PORT --workers=4 communikit:wsgi
