# Generated by Django 2.2.2 on 2019-07-29 21:20

from django.conf import settings
from django.db import migrations


def move_subscriptions(apps, schema_editor):

    user_app, user_model = settings.AUTH_USER_MODEL.split(".")

    Subscription = apps.get_model("subscriptions", "Subscription")
    User = apps.get_model(user_app, user_model)
    Tag = apps.get_model("taggit", "tag")

    for subscription in Subscription.objects.all():
        subscriber = subscription.subscriber
        object_id = subscription.object_id
        ct = subscription.content_type
        if ct.model == "tag" and ct.app_label == "taggit":
            tag = Tag.objects.get(pk=object_id)
            subscriber.following_tags.add(tag)
        elif ct.model == "user" and ct.app_label == "users":
            user = User.objects.get(pk=object_id)
            subscriber.following.add(user)


class Migration(migrations.Migration):
    dependencies = [("subscriptions", "0003_auto_20190705_1857")]
    operations = [
        migrations.RunPython(move_subscriptions, migrations.RunPython.noop)
    ]
