# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM node:12.16.1-slim

COPY webpack.config.js ./webpack.config.js
COPY postcss.config.js ./postcss.config.js
COPY tailwind.config.js ./tailwind.config.js
COPY package.json ./package.json
COPY yarn.lock ./yarn.lock

RUN yarn

WORKDIR /app
