# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0
  DJANGO_SECRET_KEY: seekrit

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.7
    environment:
      # for testing only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    restart: always

  vue:
    build:
      context: frontend
      cache_from:
        - '${CI_REGISTRY_IMAGE-deploy}/vue:${CI_COMMIT_SHORT_SHA-deploy}'
    image: '${CI_REGISTRY_IMAGE-deploy}/vue:${CI_COMMIT_SHORT_SHA-deploy}'
    volumes:
      - .:/app
      - /app/node_modules

  django: &django
    build:
      context: .
      dockerfile: Dockerfile.deploy
      cache_from:
        - '${CI_REGISTRY_IMAGE-deploy}/django:${CI_COMMIT_SHORT_SHA-deploy}'
    image: '${CI_REGISTRY_IMAGE-deploy}/django:${CI_COMMIT_SHORT_SHA-deploy}'
    environment: *default-env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
