# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM python:3.8.2-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && apt-get install -y postgresql

# Copy requirements to insure caching
COPY ./requirements.txt /requirements.txt
RUN pip install -U pip && pip install -r /requirements.txt

WORKDIR /app
COPY . /app

RUN useradd -m user
USER user
