# Generated by Django 2.2.4 on 2019-08-13 15:15

from django.db import migrations, models

import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0009_auto_20190804_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="logo",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                help_text="Logo will be displayed in a 100x100 pixel square.",
                null=True,
                upload_to="logo",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="logo",
            field=models.TextField(
                blank=True,
                help_text="Logo will be displayed in a 100x100 pixel square.",
                max_length=100,
                null=True,
            ),
        ),
    ]
