# Generated by Django 2.2.4 on 2019-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0011_auto_20190814_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="blacklisted_email_addresses",
            field=models.TextField(
                blank=True,
                help_text="Join requests from these addresses will be automatically rejected. Separate with spaces.",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="blacklisted_email_domains",
            field=models.TextField(
                blank=True,
                help_text="Join requests from these domains will be automatically rejected. Separate with spaces.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="blacklisted_email_addresses",
            field=models.TextField(
                blank=True,
                help_text="Join requests from these addresses will be automatically rejected. Separate with spaces.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="blacklisted_email_domains",
            field=models.TextField(
                blank=True,
                help_text="Join requests from these domains will be automatically rejected. Separate with spaces.",
            ),
        ),
    ]
