# Generated by Django 2.2.4 on 2019-09-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20190906_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_join_requests',
            field=models.BooleanField(default=True, help_text='Users can send requests to join this community. If disabled they will only be able to join if an admin sends them an invite.'),
        ),
        migrations.AddField(
            model_name='historicalcommunity',
            name='allow_join_requests',
            field=models.BooleanField(default=True, help_text='Users can send requests to join this community. If disabled they will only be able to join if an admin sends them an invite.'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tagline',
            field=models.TextField(blank=True, help_text='Summary shown in your Local Network.'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='tagline',
            field=models.TextField(blank=True, help_text='Summary shown in your Local Network.'),
        ),
    ]
