# Generated by Django 2.2.4 on 2019-09-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_auto_20190908_1023'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='community',
            managers=[
            ],
        ),
    ]
