# Generated by Django 3.0.3 on 2020-03-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_auto_20200216_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='historicalcommunity',
            name='admin',
        ),
    ]
