# Generated by Django 3.0.3 on 2020-03-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_auto_20200305_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='listed',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='historicalcommunity',
            old_name='listed',
            new_name='public',
        ),
    ]
