# Generated by Django 3.0.4 on 2020-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0021_auto_20200305_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Community is visible to non-members in Communities page.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Community is visible to non-members in Communities page.",
            ),
        ),
    ]
