# Generated by Django 3.0.5 on 2020-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0023_auto_20200312_0925"),
    ]

    operations = [
        migrations.DeleteModel(name="HistoricalCommunity",),
    ]
