# Generated by Django 2.2 on 2019-05-30 10:27

import communikit.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', communikit.users.models.UserManager()),
            ],
        ),
    ]
