# Generated by Django 2.2.2 on 2019-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["owner", "community"], name="photos_phot_owner_i_23fd94_idx"
            ),
        ),
    ]
