# Generated by Django 2.2.2 on 2019-07-20 10:00

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localhub.common.markdown.fields
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_community_content_warning_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0006_remove_photo_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPhoto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', localhub.common.markdown.fields.MarkdownField(blank=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('title', models.CharField(max_length=300)),
                ('image', models.TextField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('original_url', models.URLField(blank=True, null=True)),
                ('cc_license', models.CharField(blank=True, choices=[('by', 'Attribution'), ('by-sa', 'Attribution ShareAlike'), ('by-nd', 'Attribution NoDerivs'), ('by-nc', 'Attribution NonCommercial'), ('by-nc-sa', 'Attribution NonCommercial ShareAlike'), ('by-nc-nd', 'Attribution NonCommercial NoDerivs')], max_length=10, null=True, verbose_name='Creative Commons license')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('community', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='communities.Community')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical photo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
