# Generated by Django 2.2.7 on 2019-11-21 18:09

from django.db import migrations
from django.db.models import F


def set_default_published(apps, schema_editor):
    apps.get_model("photos", "Photo").objects.filter(published__isnull=True).update(
        published=F("created")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0015_auto_20191121_1540"),
    ]

    operations = [migrations.RunPython(set_default_published)]
