# Generated by Django 3.0.2 on 2020-02-02 10:19

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0016_auto_20191121_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphoto",
            name="image",
            field=models.TextField(
                help_text="For best results, photos should be no larger than 1MB. If the image is too large it will not be accepted.",
                max_length=100,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="For best results, photos should be no larger than 1MB. If the image is too large it will not be accepted.",
                upload_to="photos",
                verbose_name="Photo",
            ),
        ),
    ]
