# Generated by Django 3.0.4 on 2020-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0021_auto_20200318_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphoto",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalphoto",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
