# Generated by Django 2.2.2 on 2019-07-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_auto_20190719_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community'),
        ),
    ]
