# Generated by Django 2.2.4 on 2019-08-04 12:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_auto_20190724_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='messageboar_search__294887_gin'),
        ),
    ]
