# Generated by Django 2.2.4 on 2019-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0006_auto_20190804_1253'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created', '-created'], name='messageboar_created_471c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['read'], name='messageboar_read_fa458b_idx'),
        ),
    ]
