# Generated by Django 2.2.4 on 2019-08-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0007_auto_20190812_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.Community'),
        ),
    ]
