# Generated by Django 2.2.4 on 2019-08-22 17:45

from django.contrib.postgres.search import SearchVector
from django.db import migrations, models


def do_migration(apps, schema_editor):

    MessageRecipient = apps.get_model("messageboard", "MessageRecipient")
    Message = apps.get_model("conversations", "Message")

    for recipient in MessageRecipient.objects.select_related(
        "message", "message__sender", "recipient", "message__community"
    ):

        message_body = (
            recipient.message.subject + "\r\n" + recipient.message.message
        )

        search_doc = SearchVector(
            models.Value(message_body, output_field=models.CharField()),
            weight="A",
        )

        message = Message.objects.create(
            message=message_body,
            sender=recipient.message.sender,
            recipient=recipient.recipient,
            search_document=search_doc,
            community=recipient.message.community,
            read=recipient.read,
        )
        # explicitly set timestamp
        message.created = message.updated = recipient.message.created
        message.save()


class Migration(migrations.Migration):

    dependencies = [("messageboard", "0008_auto_20190822_1617")]

    operations = [migrations.RunPython(do_migration)]
