# Generated by Django 2.2 on 2019-04-25 18:41

import communikit.communities.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='community',
            managers=[
                ('objects', communikit.communities.models.CommunityManager()),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='domain',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='This is not a valid domain', regex='([a-z¡-\uffff0-9](?:[a-z¡-\uffff0-9-]{0,61}[a-z¡-\uffff0-9])?(?:\\.(?!-)[a-z¡-\uffff0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z¡-\uffff-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost)')]),
        ),
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='sites.Site'),
        ),
    ]
