# Generated by Django 2.2 on 2019-04-25 18:42

from django.db import migrations


def move_sites_to_domains(apps, schema_editor):

    Community = apps.get_model("communities", "Community")
    for community in Community.objects.filter(site__isnull=False):
        community.domain = community.site.domain
        community.save()


class Migration(migrations.Migration):

    dependencies = [("communities", "0002_auto_20190425_1841")]

    operations = [migrations.RunPython(move_sites_to_domains)]
