# Generated by Django 2.2 on 2019-05-07 20:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20190425_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
