# Generated by Django 2.2 on 2019-05-18 10:13

import communikit.core.markdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20190514_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=communikit.core.markdown.fields.MarkdownField(blank=True),
        ),
    ]
