# Generated by Django 2.2.4 on 2019-08-21 08:46

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localhub.core.markdown.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0011_auto_20190814_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', localhub.core.markdown.fields.MarkdownField()),
                ('search_document', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.Community')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='conversatio_search__3fb11b_gin'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created', '-created'], name='conversatio_created_82554d_idx'),
        ),
    ]
