# Generated by Django 2.2.4 on 2019-08-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='conversatio_created_82554d_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created', '-created', 'read'], name='conversatio_created_535baa_idx'),
        ),
    ]
