# Generated by Django 2.2.4 on 2019-08-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20190821_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community'),
        ),
    ]
