# Generated by Django 2.2.4 on 2019-08-25 09:45

from django.db import migrations


def do_migration(apps, schema_editor):
    try:
        PM_Message = apps.get_model("private_messages.Message")
        ConversationMessage = apps.get_model("conversations.Message")
    except LookupError:
        # skip
        return

    for msg in ConversationMessage.objects.all():
        new_msg = PM_Message.objects.create(
            id=msg.id,
            community=msg.community,
            sender=msg.sender,
            recipient=msg.recipient,
            message=msg.message,
            read=msg.read,
            search_document=msg.search_document,
        )
        new_msg.created = msg.created
        new_msg.modified = msg.modified
        new_msg.save()

    for parent in ConversationMessage.objects.filter(parent__isnull=False):
        for reply in ConversationMessage.objects.filter(parent=parent):
            new_msg = PM_Message.objects.get(id=reply.id)
            new_msg.parent_id = parent.id
            new_msg.save()


class Migration(migrations.Migration):

    dependencies = [("conversations", "0004_message_parent")]

    operations = [migrations.RunPython(do_migration)]
