# Generated by Django 2.2 on 2019-05-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20190507_2032'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('email', 'community')},
        ),
    ]
