# Generated by Django 2.2 on 2019-05-10 20:14

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_auto_20190509_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
