# Generated by Django 3.0.5 on 2020-04-23 03:12

# Django
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# Third Party Libraries
import model_utils.fields

# Social-BFG
import social_bfg.apps.hashtags.fields
import social_bfg.apps.users.fields
import social_bfg.common.markdown.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hashtags",
                    social_bfg.apps.hashtags.fields.HashtagsField(
                        blank=True, max_length=300
                    ),
                ),
                (
                    "mentions",
                    social_bfg.apps.users.fields.MentionsField(
                        blank=True, max_length=300
                    ),
                ),
                (
                    "description",
                    social_bfg.common.markdown.fields.MarkdownField(blank=True),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("is_reshare", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("edited", models.DateTimeField(blank=True, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("opengraph_image", models.URLField(blank=True, max_length=500)),
                ("opengraph_description", models.TextField(blank=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.Community",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
