# Generated by Django 3.0.5 on 2020-04-23 03:12

# Django
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Third Party Libraries
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("polls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reshares",
                to="polls.Poll",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="polls.Poll",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="voters",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="polls_poll_search__666b21_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["created", "-created"], name="polls_poll_created_b81dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["published", "-published"], name="polls_poll_publish_26bf3b_idx"
            ),
        ),
    ]
