# Generated by Django 2.2 on 2019-05-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activity_content_type',
            new_name='activity_type',
        ),
    ]
