# Generated by Django 2.2 on 2019-05-18 13:39

import communikit.core.markdown.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', communikit.core.markdown.fields.MarkdownField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.activity',),
        ),
    ]
