# Generated by Django 2.2 on 2019-05-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnotification',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.Post'),
        ),
    ]
