# Generated by Django 2.2.2 on 2019-06-07 12:31

import communikit.core.markdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=communikit.core.markdown.fields.MarkdownField(blank=True),
        ),
    ]
