# Generated by Django 2.2 on 2019-05-30 09:22

import communikit.core.markdown.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('description', communikit.core.markdown.fields.MarkdownField(blank=True)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200, verbose_name='City or town')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.activity',),
        ),
    ]
