# Generated by Django 2.2.2 on 2019-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starts',
            field=models.DateTimeField(verbose_name='Starts on (UTC)'),
        ),
    ]
