# Generated by Django 2.2 on 2019-04-28 21:49

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
