# Generated by Django 2.2.2 on 2019-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190530_0922'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id', 'community', 'actor', 'recipient'], name='notificatio_content_4d6bd8_idx'),
        ),
    ]
