# Generated by Django 2.2.4 on 2019-08-03 15:29

from django.db import migrations

ACTIVITY_VERBS = (
    ("delete", "moderator_delete"),
    ("edit", "moderator_edit"),
    ("follow", "new_followed_user_post"),
    ("following", "new_followed_user_post"),
    ("tag", "new_followed_tag_post"),
    ("review", "moderator_review_request"),
)

COMMENT_VERBS = (
    ("comment", "new_comment"),
    ("delete", "moderator_delete"),
    ("edit", "moderator_edit"),
    ("review", "moderator_review_request"),
)

MESSAGE_VERBS = (("message", "new_message"),)

USER_VERBS = (("follow", "new_follower"),)


def change_verbs(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")

    notifications = Notification.objects.filter(
        content_type__app_label__in=("posts", "photos", "events")
    )

    for old_verb, new_verb in ACTIVITY_VERBS:
        notifications.filter(verb=old_verb).update(verb=new_verb)

    notifications = Notification.objects.filter(
        content_type__app_label="comments"
    )

    for old_verb, new_verb in COMMENT_VERBS:
        notifications.filter(verb=old_verb).update(verb=new_verb)

    notifications = Notification.objects.filter(
        content_type__app_label="users"
    )

    for old_verb, new_verb in USER_VERBS:
        notifications.filter(verb=old_verb).update(verb=new_verb)

    notifications = Notification.objects.filter(
        content_type__app_label="messageboard"
    )

    for old_verb, new_verb in MESSAGE_VERBS:
        notifications.filter(verb=old_verb).update(verb=new_verb)


class Migration(migrations.Migration):

    dependencies = [("notifications", "0004_auto_20190803_1409")]

    operations = [
        migrations.RunPython(
            change_verbs, reverse_code=migrations.RunPython.noop
        )
    ]
