# Generated by Django 3.0.4 on 2020-03-19 11:39

from django.db import migrations


def remove_notifications(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(verb="moderator_review").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_rename_notification_verbs"),
    ]

    operations = [migrations.RunPython(remove_notifications)]
