# Generated by Django 3.0.5 on 2020-04-23 03:12

# Django
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Third Party Libraries
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reshares",
                to="photos.Photo",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="photos_phot_search__e98fe7_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["created", "-created"], name="photos_phot_created_7dea62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["published", "-published"],
                name="photos_phot_publish_dbe9aa_idx",
            ),
        ),
    ]
