# Generated by Django 3.0.7 on 2020-06-25 12:53

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200503_2221"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="user", name="users_user_name_211263_idx",),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["name", "username"], name="users_user_name_f99ef3_idx"
            ),
        ),
    ]
