# Generated by Django 3.0.5 on 2020-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20200423_0312"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="repeats",
            field=models.CharField(
                choices=[
                    ("day", "Same time every day"),
                    ("week", "Same day of the week at the same time"),
                    ("month", "First day of the month at the same time"),
                    ("year", "Same date and time every year"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repeats_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
