# Generated by Django 2.2.2 on 2019-07-07 09:39

from django.db import migrations

import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20190707_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
