# Generated by Django 2.2.2 on 2019-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190720_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
