# Generated by Django 2.2.2 on 2019-08-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190729_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reshares', to='events.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='reshared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='reshared',
            field=models.BooleanField(default=False),
        ),
    ]
