# Generated by Django 2.2.4 on 2019-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_auto_20190801_0717"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event", name="events_even_owner_i_ccb78f_idx",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created", "-created"], name="events_even_created_39a842_idx"
            ),
        ),
    ]
