# Generated by Django 3.0.3 on 2020-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_auto_20200221_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="title", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
