# Generated by Django 3.0.3 on 2020-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_auto_20200225_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
