# Generated by Django 3.0.5 on 2020-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="canceled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="canceled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
