# Generated by Django 3.0.5 on 2020-04-19 13:30

from django.db import migrations, models

import localhub.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_auto_20200414_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="mentions",
            field=models.CharField(
                blank=True,
                max_length=300,
                validators=[localhub.users.validators.validate_mentions],
            ),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="mentions",
            field=models.CharField(
                blank=True,
                max_length=300,
                validators=[localhub.users.validators.validate_mentions],
            ),
        ),
    ]
