# Generated by Django 3.0.5 on 2020-04-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_auto_20200419_1436"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["starts"], name="event_starts_idx"),
        ),
    ]
