# Generated by Django 3.0.5 on 2020-04-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_auto_20200419_2018"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="additional_tags", new_name="hashtags",
        ),
        migrations.RenameField(
            model_name="historicalevent",
            old_name="additional_tags",
            new_name="hashtags",
        ),
    ]
