# Generated by Django 2.2.4 on 2019-08-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0003_auto_20190825_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
    ]
