# Generated by Django 2.2.5 on 2019-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0005_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
