# Generated by Django 3.0.3 on 2020-02-26 11:21

from django.db import migrations
from django.utils import timezone


def set_recipient_deleted(apps, schema_editor):
    Message = apps.get_model("private_messages", "Message")
    Message.objects.filter(is_hidden=True).update(recipient_deleted=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0009_auto_20200226_1120'),
    ]

    operations = [
        migrations.RunPython(set_recipient_deleted)
    ]
