# Generated by Django 3.0.3 on 2020-02-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0010_set_receipient_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_hidden',
        ),
    ]
