# Generated by Django 2.2.2 on 2019-06-08 07:50

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190530_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
