# Generated by Django 2.2.2 on 2019-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
