# Generated by Django 3.0.3 on 2020-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20190830_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
