# Generated by Django 3.0.4 on 2020-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20200221_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
