#!/usr/bin/env bash

# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# shortcut to run Django manage commands under docker compose

docker-compose -f local.yml exec django ./manage.py $@

