# Generated by Django 2.2.4 on 2019-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0003_auto_20190705_1857'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flag',
            name='flags_flag_user_id_8a58cc_idx',
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['content_type', 'object_id', 'created', '-created'], name='flags_flag_content_3d6afd_idx'),
        ),
    ]
