# Generated by Django 2.2.2 on 2019-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190705_1846'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_content_65ea15_idx',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['content_type', 'object_id', 'subscriber', 'community'], name='subscriptio_content_436584_idx'),
        ),
    ]
