# Generated by Django 3.0.5 on 2020-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English (US)"),
                    ("en-gb", "English (GB)"),
                    ("fi", "Suomi"),
                ],
                default="en",
                max_length=6,
            ),
        ),
    ]
