# Generated by Django 2.2.2 on 2019-06-15 15:32

import localite.core.markdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=localite.core.markdown.fields.MarkdownField(blank=True),
        ),
    ]
